- name: install supervisor (Alpine)
  shell: apk add supervisor
- name: mkdir for supervisor (Alpine)
  shell: |
    mkdir -p /etc/supervisor/conf.d
    mkdir /var/log/supervisor
- name: configure supervisor (Alpine)
  template: src=supervisord.conf.j2 dest=/etc/supervisord.conf
